# Generated by Django 3.0.5 on 2020-05-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_webapp', '0002_auto_20200503_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
