# Generated by Django 3.0.5 on 2020-05-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_webapp', '0003_auto_20200503_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
